### ISSUE TITLE
"operation:" construct is not recognized by parser

### ISSUE THREAD

**Issue by rqc** [CloudSlang/cloud-slang#162]
Hi guys,

First of all, thank you for this tool. I am starting to learn how it works with the objective of using it for DevOps applications. Going through your documentation here: http://www.openscore.io/#/docs I was trying your [hello world](http://www.openscore.io/#/docs#hello-world-example) example and it I was getting the following error:

```
Command failed java.lang.RuntimeException: java.lang.RuntimeException: There was
 a problem parsing the YAML source: print.sl.
Cannot create property=operation for JavaBean=org.openscore.lang.compiler.model.
ParsedSlang@18e8eab
 in 'string', line 2, column 1:
    operation:
    ^
```

I then went through some of the examples you have under `slang/content` directory and none of them use `operation:` rather they use `operations:` and create a list for each operation. My resulting hello world ran after I had it like this:

```
# hello_world.sl
namespace: ricardo
imports:
  ops: ricardo

flow:
  name: hello_world
  # inputs:
  workflow:
    sayHi:
      do:
        ops.print:
          - text: "'Hello, World!'"
```

```
# print.sl
namespace: ricardo

operations:
  - print:
      inputs:
        - text
      action:
        python_script: print text
      results:
        - SUCCESS
```

Do you think I am doing something wrong? I am using version `0.1.229`.

Thanks!

Ricardo
