### ISSUE TITLE
Running flow with non-overridable input without default value succeeds in the CLI (should fail)

### ISSUE THREAD

**Issue by einatneu** [CloudSlang/cloud-slang#200]
Run the following flow in the CLI, it succeeds: (flow has non-overridable input without default value)

namespace: simplecp
imports:
  ops: simplecp.operations
flow:
  inputs:
    - input:
        overridable: false
  name: flow_with_non_overridable_input_without_default_value
  workflow:
    - print:
        do:
          ops.print:
            - text: input
  outputs:
    - returnResult: input
  results:
    - SUCCESS
    - FAILURE

**Comment by meshipeer** [comment]
during bug hunt: overridable = false don’t work at all!!!

**Comment by Bonczidai** [comment]
`flow has non-overridable input without default value` -- well, actually this isnn't true.. the default value in this case is the input name (as a variable). These examples have the same effect:

```yaml
inputs:
- input:
    overridable: false
    
--->

inputs:
- input:
    default: input
    overridable: false
```

so the behaviour is the expected one (`--i input=abc` runs normally and if the input is not passed we get a script evaluation error).

Shoud we accept only inputs with `default` property explicitly declared when we supply the input in map form (?) :
```yaml
- input:
    default: input
    overridable: false
```
