### ISSUE TITLE
import of files from the same folder is required - not clear why

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#216]

**Comment by Bonczidai** [comment]
@oritstone @orius123 could you please elaborate on this enhancement?

**Comment by orius123** [comment]
if you have flow and operation in the same namespace we thought it would be nice not to have to import it. and just use it as is.

**Comment by Bonczidai** [comment]
```
namespace: io.cloudslang.docker.containers

imports:
  ssh: io.cloudslang.base.remote_command_execution.ssh

flow:
  workflow:
    - with_alias:
        do:
         ssh.ssh_flow:
            - host
            - port:
                required: false

    - without_alias:
        do:
         clear_containers:
            - host
            - port:
                required: false
```

how about this syntax? no import and excplicit alias for current folder .. WDYT?
