### ISSUE TITLE
Change 'fromInputs' key to executable name

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#258]
instead of using this not so nice key, 
we can use the executable name.
i.e

```yaml
operation:
  name: baba
  inputs:
    - some_input
...
  publish:
    - some_output: baba['some_input']
```
