### ISSUE TITLE
async_loop - prints wrong color

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang#282]
Sometimes in an async_loop a print call from an operation will print in the color of task names instead of white:

![image](https://cloud.githubusercontent.com/assets/9436355/7364216/9b567132-ed8c-11e4-9d12-e3744f4ae330.png)

Flow:
```yaml
namespace: test_code.async

imports:
  ops: test_code.async

flow:
  name: async_loop_navigate
  inputs:
    - values: range(1, 10)
  workflow:
    - print_values:
        async_loop:
          for: value in values
          do:
            ops.print_branch:
              - ID: value
        navigate:
            SUCCESS: SUCCESS
            FAILURE: FAILURE
```

Operation:
```yaml
namespace: test_code.async

operation:
  name: print_branch
  inputs:
     - ID
  action:
    python_script: |
        name = 'b' + str(ID)
        print 'Hello from ' + name
  outputs:
    - name
```
