### ISSUE TITLE
Task arguments act like inputs

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#288]
for example they perform the required logic and in cast that a required input is not available fail the flow instead of passing the value as-is

**Comment by Bonczidai** [comment]
Let's decide the syntax and behavior we want, so ..

Task arguments will not behave (in general) like flow / operation inputs.
Task arguments will have a name and a default value (expression) which will be evaluated and passed to the task (similar behavior to `overridable: false`). They will **not** support the following input modifiers: system property, overridable, encrypted.

Need to decide what should happen in case of the `required` tag. I think that here we should either support the tag or make `required: false` the default - since it is common use case to pass optional values all over the flows

When naming should we go with `task inputs` or `task arguments` (other suggestion) ?

@meirwah @orius123 WDYT on this?

**Comment by orius123** [comment]
I think that task arguments should act like function arguments in python. and come up with oneliner.
for example `containers.pull_container: host = 'localhost', port = 8080`
or even `containers.pull_container(host = 'localhost', port = 8080)`
Regarding `required` I think it is the operation/sub-flow responsibility

**Comment by Bonczidai** [comment]
also need to consider the large number of task arguments & we should align to yaml syntax - so here are a couple of suggestions..

What do you prefer? Suggestions?

`#1`
```yaml
    - get_containers_in_cluster:
        do:
          containers.get_filtered_containers(docker_options, all_containers = true, excluded_images = excluded, host = 'localhost', port, username, password, private_key_file, character_set, pty, timeout = 300000, close_session, agent_forwarding)
        publish:
          - container_ids
```

`#2`
```yaml
    - get_containers_in_cluster:
        do:
          containers.get_filtered_containers: >
            docker_options, all_containers = true, excluded_images = excluded, host = 'localhost', port,
            username, password, private_key_file, character_set, pty, timeout = 300000, close_session, agent_forwarding
        publish:
          - container_ids
```

`#3`
```yaml
    - get_containers_in_cluster:
        do:
          containers.get_filtered_containers:
            - docker_options
            - all_containers: true
            - excluded_images: excluded
            - host: 'localhost'
            - port
            - username
            - password
            - private_key_file
            - character_set
            - pty
            - timeout: 300000
            - close_session
            - agent_forwarding
        publish:
          - container_ids
```
