### ISSUE TITLE
Add option to refer to full op path without import

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#297]
```yaml
flow:
  workflow:
    some_task:
      do:
        full.op.path:
          ...
```

**Comment by Bonczidai** [comment]
Consider:

```yaml
namespace: loops

imports:
  ops: a.b.c.ops

flow:
  workflow:
    - print_values:
          do:
            ops.print
```

since `ops` is in import section, it can be interpreted as *alias* or *full_path* identifier.. which one do you think should take precedence? Maybe try to resolve both?
@oritstone @meirwah

**Comment by orius123** [comment]
@Bonczidai maybe I'm missing something here, but isn't what you are suggesting is how it works today already?

**Comment by Bonczidai** [comment]
<< right, my previous comment was phrased stupidly >>
so, what I'd like to clarify is the following:
when we have sthg like (`prefix.executable`) :

```yaml
namespace: n_space

imports:
  alias: a.b.c.ops

flow:
  workflow:
    - task1:
          do:
            alias.print:

    - task2:
          do:
            fullpath.print:
```

`task1` resolved with alias (how currently works) -> **a.b.c.ops.print**
`task2` should be resolved as full path (since there is no alias `fullpath`) -> **fullpath.print**

Is this correct or I am the one who misses something?

**Comment by orius123** [comment]
And it works also when you have no imports. Right?

**Comment by Bonczidai** [comment]
yes -- I will add tests for the different cases

**Comment by oritstone** [comment]
@Bonczidai what happens in the example above if there is a print operation under: `a.b.c.ops` and also in the path `alias`
How will you know if you should look for a path with that name or the use the alias?

**Comment by orius123** [comment]
It will be unpredictable just like when you have two equal namespaces.

**Comment by orius123** [comment]
Can I continue the path after the alias? 
If I have an operation at `a.b.c.print`
Something like:
```yaml
ops: a.b
...
  do:
    ops.c.print
```
