### ISSUE TITLE
Support do keyword w/o args

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#298]
today you need to put ':' after the op name
today:
```yaml
...
    some_task:
      do:
        op_wo_args:
    next_task
    ...
```
suggested
```yaml
...
    some_task:
      do:
        op_wo_args
   next_task
    ...
```
