### ISSUE TITLE
fail compilation if task is not wired

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#305]
if we have a flow
```yaml
task1:
  ...
  navigate:
    SUCCESS: SUCCESS
    FAILURE: FAILURE
task2:
  ...
```
because task2 is not wired and therefore not accessible at runtime we don't compile it..
