### ISSUE TITLE
Modules are not cleared between python script invocations

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#405]
for example this flow fails:
```yaml
action:
   python_script: |
     import svn.local
```
but if you import io before it works:
```yaml
action:
   python_script: |
     import io
     import svn.local
```

The problem is that if you don't restart the shell import io will not help (because we don't clean up sys.moudules?)
