### ISSUE TITLE
Update file flow question

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/cloud-slang#407]
Hi
I'm trying to create a flow that updates a file
This flow has 2 steps,
1. read the file's content
2. Write an updated content to the file

the problem is that on the write task, the flow doesn't use the updated value, it's using the value from the flow's input so instead of updating the file's content it's just overriding the content with my input
Maybe i'm missing something
this is the flow:

```yaml

namespace: update_file.flow
imports:
  files: io.cloudslang.base.files

flow:
  name: files_and_folders
  
  inputs:
   - file_path
   - text
  
  workflow:
    - ReadFile:
        do:
         files.read_from_file:
               - file_path
        publish:
          - read_text: read_text

    - UpdateFile:
        do:
               files.write_to_file:
               - file_path
               - text: "read_text + '\n' + text" 
```

**Comment by meirwah** [comment]
why you need "text" as flow input , if you are not using it???

**Comment by nirgur** [comment]
why not? see last line

**Comment by meirwah** [comment]
anyway you need to use the: 
overridable: false

since by default , the inputs are "assignedFrom=true"  , it will take the input from the existing context...

**Comment by meirwah** [comment]
see example at : http://www.cloudslang.io/#/docs#inputs

**Comment by nirgur** [comment]
i'm not sure I understand
which input I need to set as overridable: false??
My problem is that the "text" input of the write_to_file operation is using the flow's "text" input instead of the concatenated string

**Comment by meirwah** [comment]
input "text" in task "UpdateFile", that way it will become "assignedFrom=false" , and use the right context for the value

**Comment by orius123** [comment]
I think it's #288 all over again...
make the task `text` input:
```yaml
- text: 
    default: "read_text + '\n' + text"
    overridable: false
```

or change the flow inputs to something like
`suffix` / `extra_text` / `user_addition` ...
