### ISSUE TITLE
publish indentation(Yaml) issue

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#409]
in this flow : 
 
workflow:
    - sshTest:
        do:
          ssh.ssh_command:
            - username: "'xxx'"
          publish:
            - returnResult
            - standard_out
            - standard_err

publish does not work (vertical indentation issue, Yaml), but user has no way to know that (other then getting the returnResults empty values), maybe compiler should notice this? IDE to solve this?

**Comment by oritstone** [comment]
@meirwah the example you pasted does not pass compilation...
Can you attach a file with the entire flow o we can refer it?

**Comment by meirwah** [comment]
```
namespace: tutorials.base

imports:
  ops: io.cloudslang.base.print
  ssh: io.cloudslang.base.remote_command_execution.ssh

flow:
  name: hello_world
  workflow:
    - sshTest:
        do:
          ssh.ssh_command:
            - host: "'some-ip"
            - command: "'ifconfig'"
            - username: "'xxx'"
            - password: "'xxx'"
          publish:
            - returnResult
            - standard_out
            - standard_err
    - printResults1:
         do:
           ops.print_text:
             - returnResult
             - text: "'end'+returnResult"
    - printResults2:
         do:
           ops.print_text:
             - text: "' '+standard_err"


  #         ops.print_text:
   #          - text: standard_out
#           ops.print_text:
#             - text: standard_err
      results:
        - SUCCESS: returnCode == '0'
        - FAILURE
  outputs:
    - returnResult
    - standard_out
    - standard_err
```
