### ISSUE TITLE
Error message when flow & operation has the same input name

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/cloud-slang#410]
Run this flow and see that you're getting an error message on the input text
change the flow's input name from text to something else and see that everything is working

```yaml
namespace: update_file.flow
imports:
  files: io.cloudslang.base.files
  print: io.cloudslang.base.print
  utils: io.cloudslang.base.utils

flow:
  name: update_file
  
  inputs:
   - file_path
   - text
  
  workflow:
    - ReadFile:
        do:
         files.read_from_file:
         - file_path
        publish:
          - read_text
         
    - UpdateFile:
        do:
         files.write_to_file:
         - file_path
         - text:
            default: "read_text + '\\n' + text"
            overridable: false
            
    - Sleep:
        do:
         utils.sleep:
         - seconds: 0
```

**Comment by orius123** [comment]
Nice catch.
#288 is killing us! :skull: 

I believe that the problem is that somehow override the text value here.

**Comment by meirwah** [comment]
What do you mean @orius123  ?

**Comment by orius123** [comment]
when I run:
```yaml
 - text:
            default: type(text)
            overridable: false
```
I get <None>, but since it should have value that I gave on triggering, my best guess is that we override it with empty value.
