### ISSUE TITLE
Python script include a module library from google-api-python-client [1]

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/cloud-slang#449]
Hello,

In order to be able to authenticate to Google APIs, I would like create a Python Script action using google-api-python-client provided by google for Python library (https://developers.google.com/api-client-library/python/start/installation)

How could I include google-api-python-client library inside CloudSlang please ? Any ideas ?

More details below 

After having installed google-api-python-client correctly in laptop, I can execute a python standalone script to do the authentification 
```python
#!/usr/bin/env python
import argparse
import json
import os

from apiclient import discovery
from oauth2client.client import GoogleCredentials
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'C:\\Users\\bettanm\\Documents\\GitHub\\cloud-slang-content\\content\\io\\cloudslang\\cloud_provider\\gke\\cloudslang-026ac0ebb6e0.json'
credentials = GoogleCredentials.get_application_default()
service = discovery.build('container', 'v1', credentials=credentials)
```
Unfortunately, it's not working with a YAML CloudSlang file 
```yaml
namespace: io.cloudslang.cloud_provider.gke

operation:
  name: google_auth
  inputs:
    - jSonPathauthentification:
        required: false
  action:
    python_script: |
        try:
            import argparse
            import json
            import os

            from apiclient import discovery
            from oauth2client.client import GoogleCredentials
            os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'C:\\Users\\bettanm\\Documents\\GitHub\\cloud-slang-content\\content\\io\\cloudslang\\cloud_provider\\gke\\cloudslang-026ac0ebb6e0.json'
            credentials = GoogleCredentials.get_application_default()
            service = discovery.build('container', 'v1', credentials=credentials)
        except Exception as ex:
            return_code = '-1'
            return_result = ex
  outputs:
    - return_code
    - return_result
    - error_message: return_result if return_code == '-1' else ''

  results:
    - SUCCESS: return_code == '0'
    - FAILURE
```
Thanks very much
Michaël B.
