### ISSUE TITLE
Cloudslang asks for required parameters in flow when they are optional

### ISSUE THREAD

**Issue by rqc** [CloudSlang/cloud-slang#458]
Hello,

I am using the `0.8.0` docker image to run some of the sample content that you have created. If I run it from the content that is already packaged in the docker image, there is no issue. However, when I map it to the latest clone (`master` commit `acb6e72061de1097a03c6c62173c3bf4f97bff5e`) in my host using the `-v` flag in docker, it complains that I am not passing arguments that are apparently `required`, but they are actually flagged as `required: false` in the yml files. 

Here is an example dump:

```
cslang>run --f ../content/io/cloudslang/docker/swarm/examples/print_cluster_info.sl --i swarm_manager_ip=myvmhostname,swarm_manager_port=2375,host=myvmhostname,port=22,username=root,password=mysecret
Command failed java.lang.RuntimeException: Slang Error : Error running: retrieve_cluster_info: Input with name: 'private_key_file' is Required, but value is empty
```

And the flow in `print_cluster_info.sl` looks like this:

```
namespace: io.cloudslang.docker.swarm.examples

imports:
  swarm: io.cloudslang.docker.swarm
  print: io.cloudslang.base.print

flow:
  name: print_cluster_info
  inputs:
    - swarm_manager_ip
    - swarm_manager_port
    - host
    - port:
        required: false
    - username
    - password:
        required: false
    - private_key_file:
        required: false
    - character_set:
        required: false
    - pty:
        required: false
    - timeout:
        required: false
    - close_session:
        required: false
    - agent_forwarding:
        required: false

  workflow:
    - retrieve_cluster_info:
        do:
          swarm.get_cluster_info:
            - swarm_manager_ip
            - swarm_manager_port
            - host
            - port
            - username
            - password
            - private_key_file
            - character_set
            - pty
            - timeout
            - close_session
            - agent_forwarding
        publish:
          - number_of_containers_in_cluster

    - print_number_of_containers:
        do:
          print.print_text:
            - text: >
                'Number of containers in cluster: ' + number_of_containers_in_cluster

```

Any clues into why it runs ok when it is using the version of content in the container and it is not working when mounted as a volume from the host?

Thanks!
