### ISSUE TITLE
Questions about running scripts within flows in .sl files

### ISSUE THREAD

**Issue by rqc** [CloudSlang/cloud-slang#459]
Hello,

From the documentation I understand that we can have python statements embedded within the cloudslang yml DSL. However, I could not find any references of how I could run a python script that I have created outside of the yml file. For instance if I want to reproduce a "hello world" example in this way I would first create a `hello_world.py` file as such:

```python
# !/bin/python
print "Hello World"
```
and then I would make reference of that file to run it within a cloudslang workflow:

```yml
# hello.sl
namespace: example

operation:
  name: print_text
  action:
    python_script: hello_world.py
  results:
    - SUCCESS
```

When I try this it says:

```bash
cslang>run --f ../content/example/hello.sl
Command failed java.lang.RuntimeException: Slang Error : Error executing python script: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'hello_world' is not defined
```

Is there any way in cloudslang to read / execute a file from the yaml DSL?

Can I do this using `bash` perhaps?

Thanks!

**Comment by meirwah** [comment]
try this:
http://cloudslang-docs.readthedocs.org/en/v0.8/tutorial/14_lesson/

**Comment by rqc** [comment]
OK, I moved the `hello_world.py` to the `python-lib/` directory. It still won't pick up using `python_script: hello_world.py`. Perhaps I will always need to have the `main` python script embedded and then do the `import` of the user-defined libraries / scripts?

**Comment by orius123** [comment]
I believe  that in your case just importing it will run it.
unless you wrap it with any sort of a function like `main`
`python_script: import hello_world`

not next to a computer to test it though :grimacing:

**Comment by meirwah** [comment]
Hi @rqc , so what you need to do is either : 
Make a wrapper function so that you can call from the operation , like this:
`hello_world.py` file 
```python
# !/bin/python
def print_hello():
    print "Hello World"
```

and in the operation : 
```yml
operation:
  name: hello
  action:
    python_script: |
      import hello_world
      hello_world.print_hello()
```

OR, call you python code directly from the operation : 
```yml
operation:
  name: print_text
  inputs:
    - text
  action:
    python_script: print "Hello World"
```
