### ISSUE TITLE
support flow description

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#505]

**Comment by orius123** [comment]
What do you mean?

**Comment by meshipeer** [comment]
we want to have the ability to write flow description with DSL tag
so you can, for example, get it in the CLI (only metadata)

**Comment by orius123** [comment]
Cool. :+1: :cool: 
It doesn't have to be in the DSL, it can be CLI static analysis capability also.

**Comment by Bonczidai** [comment]
here how `io.cloudslang.docker.swarm.create_cluster` would look like after putting description in DSL:

```yaml
#   (c) Copyright 2014 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################

namespace: io.cloudslang.docker.swarm

imports:
  containers: io.cloudslang.docker.containers

flow:
  name: create_cluster
  description: Creates a Swarm cluster.
  inputs:
    - swarm_image:
        default: 'swarm'
        description: Docker image used by the Swarm container
    - host:
        description: Docker machine host
    - port:
        required: false
        description: SSH port
    - username:
        description: Docker machine username
    - password:
        required: false
        description: Docker machine password
    - private_key_file:
        required: false
        description: path to private key file
    - character_set:
        required: false
        description:
          - character encoding used for input stream encoding from target machine
          - Valid: SJIS, EUC-JP, UTF-8
    - pty:
        required: false
        description:
          - whether to use PTY
          - Valid: true, false
    - timeout:
        required: false
        description: time in milliseconds to wait for the command to complete
    - close_session:
        required: false
        description:
          - >
            if false SSH session will be cached for future calls during the life of the flow,
            if true the SSH session used will be closed;
          - Valid: true, false
    - agent_forwarding:
        required: false
        description: whether to forward the user authentication agent

  workflow:
    - create_cluster:
        do:
          containers.run_container:
            - detach: false
            - container_params: '--rm'
            - container_command: 'create'
            - image_name: ${swarm_image}
            - host
            - port
            - username
            - password
            - private_key_file
            - characterSet: ${character_set}
            - pty
            - timeout
            - closeSession: ${close_session}
            - agentForwarding: ${agent_forwarding}
        publish:
          - cluster_id: ${container_id}
  outputs:
    - cluster_id:
        description: ID of the created cluster

```

it can quickly get complex - static analysis may be a good idea

**Comment by Bonczidai** [comment]
also, for inputs we couldn't have `- input: value` construct since we need description tag

**Comment by orius123** [comment]
Another approach would be to put all of the decription in the beginning of the file like we do today but with some strict format. Not saying its a better way, just another way.

**Comment by meshipeer** [comment]
i agree with orius123 - i think the inputs description in this case should be part of the flow description

**Comment by Bonczidai** [comment]
there are multiple possibilities here:

1. static analysis - comments at the beginning of the flow

```yaml
####################################################
# Creates a Swarm cluster.
#
# Inputs:
#   - swarm_image - optional - Docker image used by the Swarm container - Default: swarm (latest)
#   - host - Docker machine host
#   - port - optional - SSH port
```

2. description tag at `flow` level

```yaml
description: ...

imports:
  containers: io.cloudslang.docker.containers

flow:
  name: create_cluster
```

3. description under `flow` level

```yaml
flow:
  description: ....
  name: create_cluster
```

Also we can put everything (inputs, outputs, results) under description tag or add description tag for each input / output / result (but then we cannot have `- input: value` construct).

**Comment by Bonczidai** [comment]
please give feedback @CloudSlang/slang-functional-reviewers

**Comment by oritstone** [comment]
I prefer having all the descriptions grouped together on top, and not on each input\output\result. 
It will allow us to have the simpler syntax of `input: value` and also, I think that adding it inside, makes the flow\operation look much more cumbersome than it actually is...
I think that the 1st or 2nd options are better than the 3rd. 
Personally I think that the 2nd is best, since it is easier to enforce the presence of descriptions if we choose, and show it highlighted in a special way in Atom.

If we go with the 2nd option, we can have a syntax such as:
```yaml
description:
  flow: flow desc
  inputs:
    input1: input1 desc
    input2: input2 desc
  outputs:
    output1: output1 desc


imports:
  containers: io.cloudslang.docker.containers

flow:
  name: create_cluster
```

**Comment by orius123** [comment]
I like option #1 more. 
Don't want to add stuff to the DSL.

**Comment by ziso** [comment]
i prefer option 1, it is more standard and straightforward, no need to add meta data to DSL

**Comment by avigail-oron** [comment]
I believe we have to choose either option 2 or option 3
i prefer #2 
we need it as structured data (so additions to DSL are required) to allow the future visual editor of CloudSlang to be able to extract it in higher level of accuracy and be able to provide it as the metadata of the flow w/o the user having to open it and read through the flow/inputs/outputs descriptions in the comment

**Comment by orius123** [comment]
It doesnt mean it has to be part of the DSL, just that it need to have a strict format. 
As you said it's metadata, it's not data of the language.

**Comment by avigail-oron** [comment]
so it's an extension for the DSL. just like the layout attriibutes would be an addition to the DSL.
can you explain why you object to DSL additions?

**Comment by meshipeer** [comment]
how about use metadata flavor like --- ?

**Comment by orius123** [comment]
I don't want to add it to the language. Because it's not part of the language. Cloudslang is about describing a workflow, I don't need a description for a flow or for an input in order to run it successfully. Deciding on a format doesn't mean at all that it is part/extension of the DSL. 
Regarding layout stuff, really?? How is that even considered to be related to the DSL? That us completely IDE business.

**Comment by avigail-oron** [comment]
Agree.
so we need to separate between the need to have metadata (of various kinds) in a structured way from the need to extend the DSL.
Can we agree that the metadata should be structured with a predefined set of directives? (can be in the -- format that Meshi suggested)

Another aspect is the validity of the MD info. CloudSlang compiler should obviously ignore it alltogether. The IDE\whatever other tool that will need that data will validate the *specific* directives it's interested it. (to allow forward-compatibility). so for instance, a CloudSlang flow with corrupted layout MD will pass compilation and run but will make the IDE alert the user of problems.

**Comment by orius123** [comment]
Sounds good. I think that the --- is already taken in yaml to separate yaml objects, but than, on the other hand maybe that is what we need. It will be like storing it in different files, which is another option I won't rule out.

**Comment by Bonczidai** [comment]
so, how about changing the current .sl file headers to a structured format like the one suggested by @oritstone but as comments:

```yaml
###################################
#  Validates SSH access to the host and then runs an SSH command on the host.
#
#  Inputs:
#    - host - hostname or IP address
#    - port - optional - port number for running the command - Default: 22
#    - smart_recovery - whether the flow should try to recover in case of ssh session failure
#                     - such failure may happen because of unstable ssh connection - e.g. 'Session is down' exception
#                     - Default: true
# Outputs:
#    - standard_out - STDOUT of the machine in case of successful request, null otherwise
#    - standard_err - STDERR of the machine in case of successful request, null otherwise
# Results:
#    - SUCCESS - SSH access was successful and returned with code 0
#    - FAILURE - otherwise
###################################
```

--->

```yaml
###################################
#  description:
#    flow: validates SSH access to the host and then runs an SSH command on the host
#    inputs:
#      - host: hostname or IP address
#      - port: port number for running the command
#      - smart_recovery: |
#           whether the flow should try to recover in case of ssh session failure
#           such failure may happen because of unstable ssh connection - e.g. 'Session is down' exception
#    outputs:
#      - standard_out: STDOUT of the machine in case of successful request, null otherwise
#      - standard_err: STDERR of the machine in case of successful request, null otherwise
#    results:
#      - SUCCESS: SSH access was successful and returned with code 0
#      - FAILURE: otherwise
###################################
```

compiler would ignore these comments, later on IDE could validate / load these comments easily if we use Yaml format there

**Comment by avigail-oron** [comment]
i see a problem with this approach. comments should be free. no one expects anything to parse comments and look for patterns.
i tried to look at yaml syntax and find an appropriate way to annotate it, but didn't find anything yet. do you see additional options other than comments?

**Comment by orius123** [comment]
We can do like javadocs have the comment mark with our own modifier i.e.
**java - javadocs:**
`/* text */` -  `/** documentation */`

**YAML - cloudslang docs**
`# text` - `#(some char..) documentation`

Since YAML doesn't have block comments we are a little limited here.

Regarding layout attr, I think it can live in some IDE's project file or such, it doesn't even need to be in the dir, like intellij or eclipse projects files.

**Comment by guyhanael** [comment]
@orius123, you can not leave the layout attr outside the yaml file, as we need to support version control capabilities and I do not find it reasonable to have more than one file to commit/update

**Comment by orius123** [comment]
What do you mean by layout attributes? Is this logical attr like position/group/priority.. that the user can set and change, or some programish X and Y, that the program set. 
Because if it is program stuff I don't think it is good to put it in a user file anyway. For instance how am I going to merge it? How can I decide what is better 102.34/56.87 or 154.73/63.29? In general it is not a good approach to mix user and sodtware data.

**Comment by orius123** [comment]
Anyways, I think that if we all accept on the flow description issues, we should open a new PR for the layout attr, or take it in slack. WDYT?

**Comment by Bonczidai** [comment]
to sum up, based on the comments I see two approaches here:

`#1` DSL tags:

```yaml
description:
  flow: flow desc
  inputs:
    input1: input1 desc
    input2: |
        line 1
        line 2
  outputs:
    output1: output1 desc

imports:
  containers: io.cloudslang.docker.containers

flow:
  name: create_cluster
```

`#2` Yaml comments + Javadoc style:

```yaml
# hello CloudSlangers

#! flow: flow desc
#! inputs:
#!   input1: input1 desc
#!   input2: |
#!        line 1
#!        line 2
#! outputs:
#!   output1: output1 desc

imports:
  containers: io.cloudslang.docker.containers
 
flow:
  name: create_cluster
```

**Comment by SamMarkowitz** [comment]
Either way, I suggest having a structured way to document more info for inputs, not just a description.

Such as:

+ optional
+ default value
+ valid values
+ example

Right now it's all shoved into a description which ends up being a bit of a mess.

**Comment by meshipeer** [comment]
I prefer to go with the comments, also from backward compatibility point of view.

**Comment by meirwah** [comment]
I'm with @meshipeer , KISS

**Comment by Bonczidai** [comment]
so, we are going with the comments approach, similar to this:

```yaml
# hello CloudSlangers

#! flow:
#!   description: general desc
#!   inputs:
#!     - input1: input1 desc
#!     - input2: |
#!         input2 description
#!         optional
#!         default: default value
#!         valid: valid values
#!         example: example value
#!   outputs:
#!     - output1: output1 desc
#!   results:
#!     - result1: result1 desription
#!     - result2: result2 description

imports:
  containers: io.cloudslang.docker.containers
 
flow:
  name: create_cluster
```

the remaining question is about wording - as you see currently the top level tag is `flow`, but we also have `operation`.. I don't think using two different tags is a good approach. Maybe use other tags like `metadata` or `info`? WDTY? *All*, @tomershadi, @avigail-oron

**Comment by orius123** [comment]
Why do you need a top level word? You can just write description, inputs...
BTW I'm with the comments thing also.

**Comment by oritstone** [comment]
I agree with @orius123 . No need for the additional hierarchy

**Comment by Bonczidai** [comment]
so we can agree on this:

```yaml
# hello CloudSlangers

#! description: general desc
#! inputs:
#!   - input1: input1 desc
#!   - input2: |
#!       input2 description
#!       optional
#!       default: default value
#!       valid: valid values
#!       example: example value
#! outputs:
#!   - output1: output1 desc
#! results:
#!   - result1: result1 desription
#!   - result2: result2 description

imports:
  containers: io.cloudslang.docker.containers
 
flow:
  name: create_cluster
```

**Comment by oritstone** [comment]
@CloudSlang/slang-functional-reviewers , @ziso please give your feedback

**Comment by avigail-oron** [comment]
I agree with this approach. are we sure that '#!' is the combination we want to go with?

**Comment by gituser173** [comment]
Do you think maybe we can use '##' instead of '#!'?

**Comment by avigail-oron** [comment]
i considered that option, but  a row of ################## is often used as a divider line, so it cannot be a reserved combination

**Comment by gituser173** [comment]
those rows can be easily removed

**Comment by avigail-oron** [comment]
but you still want to advise the user of the reserved combinations, i think it'll be confusing to them.

**Comment by gituser173** [comment]
This is how it would look like:

```yaml
#   (c) Copyright 2016 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################
## description: general desc
## inputs:
##   - input1: input1 desc
##   - input2: |
##       input2 description
##       optional
##       default: default value
##       valid: valid values
##       example: example value
## outputs:
##   - output1: output1 desc
## results:
##   - result1: result1 desription
##   - result2: result2 description
####################################################

imports:
  containers: io.cloudslang.docker.containers

flow:
  name: create_cluster
```
