### ISSUE TITLE
encrypted inputs \ outputs

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#506]

**Comment by orius123** [comment]
What is the suggestion?

**Comment by Bonczidai** [comment]
duplicate of #467

**Comment by Bonczidai** [comment]
Functional requirements - Sensitive Data
-----------------------
- SD means Sensitive Data in the context, binding can be done for inputs, arguments, outputs, publish values, result expressions (InOutParams)
- SD will not be printed / displayed in the logs, events, output of the upper modules (CLI / builder)
  - check feasability: when entering SD inputs from CLI, value will not be displayed while typing
- sensitive system properties (SSP): SP value can be SD
    - support `sensitive` modifier on SP objects (when loading)
    - access mode: TODO - depends on SD decesions
- transitivity

Two approaches here:
- SD definition & management is hidden from the user:
    -  ideal case, you mark data encrypted once, then use it as is,
    -  transitivity is inferred at runtime
    -  advantage: you could use SD as inputs even if flow does not declare sensitivity
    -  problems - since we support Py expressions which need to remain general:
        -  **feasability** is a problem: e.g. `${ do_something('var') }` - how do we know `var` was constructed from SD or non SD value, it's the same for Python context (we don't have control over it)
        -  if the inference is at runtime, we cannot mark an InOutParam SD at compile time, we need to do it dynamically in the context - SD wrapper for values in the context
- mark SD explicitly all over:
    - know what you are doing, get what you define
    - access SD: `get_sensitive()` Py function, signature ~ `get_sensitive(key, default=None)`
    - we can transform an InOutParam using `sensitive` modifier
    - we know sensitivity at compile time
    - transitivity is not an issue, since we define SD explicitly
    - disadvantage:
        - cannot pass sensitive data to a flow that does not define SD for in input

**Comment by Bonczidai** [comment]
example for second case:

Operation:
```yaml
# SD - Sensitive Data
# ND - Normal (non sensitive) Data

namespace: user.ops

operation:
  name: op_enc_explicit_SD_function

  inputs:
    - host # ND
    - pass_no_expr: # SD
        default: ${get_sensitive('pass_no_expr')} # I need to know the source, whether is SD or ND
           # maybe we can create shortcut / default behavior for this case
        sensitive: true # do I want the eval result to be sensitive? - yes
    - transform_non_sensitive: # SD -> ND
        default: ${len(get_sensitive('old_pass'))}
        sensitive: false # do I want the eval result to be sensitive? - no
    - pass_sensitive_explicitly:
        default: ${do_something(get_sensitive('old_pass'))}
        sensitive: true # => compilation check: if get_sensitive() detected, need to declare sensitivity


  action:
    python_script: python_script

  outputs:
    - output_sensitive:
        default: ${my_script_result}
        sensitive: true # we can create SD outputs

  results:
    - result_name: ${cond(get_sensitive('pass_no_expr'))}
```

Flow:
```yaml
namespace: user.flows

imports:
  ops: user.ops

flow:
  name: flow_enc_explicit_SD

  inputs:
    - host
    - port
    - user
    - pass:
        sensitive: true
    - too_long:
        default: ${len(get_sensitive(pass)) > 20}
        sensitive: false # we want here Boolean not an encoded value

  workflow:
    - task1:
        do:
          ops.op_enc_explicit_SD_function:
            - pass:
                sensitive: true
            - pass_no_expr:
                default: ${get_sensitive('pass')}
                sensitive: true
        publish:
          - publish_sensitive_from_output: ${get_sensitive('output_sensitive')}
          - publish_sensitive_from_self: ${get_sensitive('output_sensitive')} # self['pass'] ?

  outputs:
    - publish_sensitive_from_output:
        sensitive: true

  results:
    - result_name
```

**Comment by Bonczidai** [comment]
@CloudSlang/slang-functional-reviewers please give feedback

**Comment by meshipeer** [comment]
i think we need to take in consideration that the data need to distribute to the worker (in the network) in the encrypted mode

**Comment by orius123** [comment]
I would go with option no.1 without he `get_sensitive` stuff. once a user put a SD it's his responsibility to understand what he is doing. he can anyways print it to stdout no matter what we will choose.
@meshipeer regarding transfer to the worker isn't that what https is all about??

**Comment by guyhanael** [comment]
@shajyhia please review this

**Comment by avigail-oron** [comment]
regarding distribution - we cannot let the author bare sole responsibility here. we need to provide means to protect the system. this is representing the admin interests.
having said that - we can rely on TLS for that (again - admin interests). there's no point in additional encryption on top of TLS (we went through this saga in OO and realized it's a mistake)
i would add to the requirements - hold the encrypted string in memory in a safe way (char[] vs string)
As for the 2 options - can we support transitivity w/o an explicit method for accessing SD?

**Comment by Bonczidai** [comment]
I think the issue here is the transitivity:
- if we go with `sensitive` modifier and `get_sensitive()` function transitivity is defined explicitly but we need to define in the flows which data will be sensitive at creation time (no flexibility)
- if would like to pass SD implicitly / hidden from the user (ideal case - define SD at runtime) we are likely to face problems: the limitation comes from the fact that we our expressions are evaluated using Python - the responsibility is delegated - we don't have control over it: e.g. ${  'abc' + var } -- how do I know whether `var` had a SD or non SD value before eval so I can mark the result accordingly?

**Comment by avigail-oron** [comment]
so there's actually only 1 option.... we must have transitivity.

**Comment by orius123** [comment]
2 questions here.
1. Can't a user print whatever he wants from a binding expression as well? Regardless of the option we choose?
2. How is saving as char array more secured? Just add one more step for the hacker. I thing `grep` and `strings` commands represent char arrays as things when possible anyways. 

And, I disagree that you can't support transitivity for option 1,it might be harder, but technically possible IMHO.

In general, why just masking and not encrypting?

**Comment by orius123** [comment]
One more please. 
What is SD for system properties? In the SP file passwords will be plain text?? I don't think users will do it, I wouldn't..

**Comment by tomershadi** [comment]
I believe requiring the Author to use get_sensitive is too strong. The reason is that he can't know whether the type is sensitive. It might become sensitive because of transitivity or because the Admin changed later the type in runtime.
This will make them use get_sensitive always.  Therefore my question is if we can always relate to params with some get() that will distinguish by itself between the sensitive and non-sensitive cases.

**Comment by avigail-oron** [comment]
@orius123  - regarding your comments:
in the actions the author can do many unsecured things. the point is not to block that (impossible) but to allow the "good" authors to work in a secured way in a convenient manner.
char[] is for in memory handling. this is a java trick to prevent info to be dumped (upon memory dump) or being inspected by tools.
since we all agree transitivity is important, i believe this should guide this discussion. if there are ways to resolve the transitivity detection problems - please suggest how.
SD for sys prop means that the real sensitive value will be provided in the runtime env.
@tomershadi - i agree with your concern. that's why i think that transitivity must be manifested in authoring time. need to think of a way to reflect it in the textual authoring...

**Comment by Bonczidai** [comment]
this is what we have so far:

```
- SD means Sensitive Data in the context, binding can be done for inputs, arguments, outputs, publish values, result expressions (InOutParams)
- SD will not be printed / displayed in the logs, events, output of the upper modules (CLI / builder)
  - check feasibility: when entering SD inputs from CLI, value will not be displayed while typing
- sensitive system properties (SSP): SP value can be SD
    - support `sensitive` modifier on SP objects (when loading)
    - access mode: get_sp()
- we support transivity for SD
- we are going with the principle that user should know wher he can get sensitive data -> get() function
- get(): get the value regardless of its sensitivity
- income of binding: expression (handles data that need to be decrypted with `get`) -> binding -> outcome of binding: sensitivity is calculated based on sensitive_modifier(this has priority over transitivity) and transitivity
  - data may be marked sensitive:
    - at compile time with `sensitive` modifier
    - at runtime because of transitivity
- host # no expression -> (logically) host: ${get(`host`)} # may be sensitive
- accessing sensitive data without get yields in error
- we will mask all action inputs and outputs (in events, logs etc)
  - action gets decrypted context and return decrypted context
- we support sensitive outputs
  - behavior similar to inputs - we need to support `sensitive` modifier on outputs
     - e.g. I want to encrypt an action output (which can come only as non sensitive data)
  - transitivity: using `get` (e.g. from executable inputs)
- we can ccess SD in result expressions
- task arguments may become sensitive only by transitivity (no sensitive modifier here)
- publish values ~ outputs
```

**Comment by Bonczidai** [comment]
sample op and flow with explanation (see comments about what data can be SD):

```yaml
# SD - Sensitive Data
# ND - Normal (non sensitive) Data

namespace: user.ops

operation:
  name: op_sensitive

  inputs:
    - host # ND / SD -> ND / SD
    - host_expr: ${ len(host) } # fail if host is sensitive
    - host_expr_safe: ${ len(get('host')) } # becomes sensitive by transitivity if host is SD
    - host_expr_safe_no_sd:
        default: ${ len(get(`host`)) }
        sensitive: false # I know that the result should not be sensitive no matter of host's sensitivity
    - password: # get('password')
        sensitive: true # ND / SD -> SD

  action:
    python_script: python_script

  outputs:
    - output_sensitive_from_action:
        default: ${ action_output } # will be sensitive
        sensitive: true
    - output_sensitive_from_inputs:
        default: ${ do_something(get(`host`)) } # may become sensitive

  results:
    - result_name: ${ cond(get(`host`)) } # we can access SD here
```

```yaml
# SD - Sensitive Data
# ND - Normal (non sensitive) Data

namespace: user.flows

imports:
  ops: user.ops

flow:
  name: flow_sensitive

  inputs:
    - host # ND / SD -> ND / SD
    - password: # get('password')
        sensitive: true # ND / SD -> SD

  workflow:
    - task1:
        do:
          ops.op_sensitive:
            - host # ND / SD
            - host_expr: ${ get('host') + 'suffix' } # ND / SD
            - pass # SD
            - pass_expr: ${ get('pass') + 'suffix' } # SD
        publish:
          - new_host:
              default: ${get('op_output')} # ND / SD depending on the output
          - new_host_enc:
              default: ${get('op_output')}
              sensitive: true # becomes SD
          - length_host:
              default: ${len(get('op_output'))}
              sensitive: false # becomes ND

  outputs:
    - new_host
    - new_host_enc
    - length_host

  results:
    - result_name
```
