### ISSUE TITLE
do_nothing capability

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#529]

**Comment by Bonczidai** [comment]
Enhancements:
- we want to be able to define custom navigation logic on task level based on subflow outputs (and task inputs => so based on the current context) - e.g. we had this problem when we wanted to define custom results for ssh_flow
- we want to add do_nothing logic to tasks (so it will not call any executable)
This way we will also be able to define advanced constructs like a switch statement (do_nothing + custom navigation).

Suggestion is the following:
```yaml
  workflow:
    - task_legacy:
        do:
          nav_op: []
        navigate:
          SUCCESS: success_step
          FAILURE: failure_step

    - task_results_overridden:
        do:
          nav_op: []
        results:
          - SUCCESS: ${new_contition()}
          - CUSTOM_1: ${new_contition()}
          - CUSTOM_2 # default result
        navigate:
          SUCCESS: task_name # syntax and rules for navigate remain valid
          CUSTOM_1: task_name
          CUSTOM_2: task_name

    - task_do_nothing:
        do: nothing / noop / nop / pass # modify TaskSteps not to call executable

    - task_switch:
        do: nothing
        results:
          - CASE_1: ${new_contition()}
          - CASE_1: ${new_contition()}
          - DEFAULT
        navigate:
          CASE_1: task_name
          CASE_1: task_name
          DEFAULT: task_name
```

changes:
- custom navigation: we will be able to override results of the subflow by adding `results` section on the task - will work similar to subflow results; that way all the other logic that refers to navigation and wiring remains unchanged (all the already existing content is valid); custom logoc is decoupled from the other sections of the task (once overridden, subflow results are ignored)
- noop: will not call an executable; does not have inputs; it can have results, navigate and publish sections - we can decide the keyword here, I'd go with ~ `nothing`, it reflects the best that we are not calling an executable here / not switching context

**Comment by Bonczidai** [comment]
- the goal here is the ability to have `do nothing` capability which is similar to an operation but does not call any action
- it will have a similar interface to flow / operation (executable) but it will not contains workflow or action section - it will have namespace, name, inputs, outputs, results
- can hold regular language elements like description, extension section
- can be called in a step as a regular executable
- will be an `.sl` file

**Comment by Bonczidai** [comment]
we have a couple of possibilities here:

`1` - it will be an operation with no action
```
namespace: a.b

operation:
  name: executable_name

  inputs: ..

  action:
    java_action: .. or
    python_action: .. or 
    pass

  outputs: ..

  results: ..
```

this approach involves effort of refactoring all the content (we recently removed `action` keyword from hierarchy)

`2` - similar to `1` but without `action` keyword
```
namespace: a.b

operation:
  name: executable_name

  inputs: ..

  noop / pass

  outputs: ..

  results: ..
```

`3` it will be a new type of executable (besides flow / op):
```
namespace: a.b

do_nothing:
  name: executable_name

  inputs: ..

  outputs: ..

  results: ..
```
we need a top-level keyword here: do_nothing, noop..
`4` - similar to `3` but in this case it will be an `executable` -- like an abstract type (you did not provide workflow or action section), this somehow suggests that it can be specified later on
```
namespace: a.b

executable:
  name: executable_name

  inputs: ..

  outputs: ..

  results: ..
```

WDYT?
