### ISSUE TITLE
enhance system properties

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#530]
need to re-check system properties behavior:
- do we want to support many in one file?
- dont we want to allow task input to use it?
- do we want to enable using it inside expression vs. know who uses it....

**Comment by orius123** [comment]
* do we want it?.. :smile:

**Comment by Bonczidai** [comment]
Requirements:
`1.` no system property in input DSL - no such construct:
```yaml
-input:
   system_property: cloudslang.user.name
```
`2.` system properties will be accessible in input and task argument expressions
    -  also accessable in outputs, results expressions, `for` and `async` loop expressions
    - not accessable directly in python actions
    - access style: function vs map ?
         --- `${ get_system_property('property') }`, `${ get_system_property('property', 'default') }` ~ `get` function
         --- `${ system_properties['property'] }` ~ `self`, `branches_context` constructs
`3.` system properties are not enforced at compile time, they will be assigned at runtime
`4.` system properties are read only
`5.` we allow many system properties in one file, as they look today:
```yaml
tutorials.hiring.domain: bcompany.com
tutorials.hiring.hostname: localhost
tutorials.hiring.port: '8080'
```
`6.` folder structure is not enforced for system property files:
a property `d.e.prop` from folder `a/b/c` retians its value regardless of parent folders -> `d.e.prop` and not `a.b.c.d.e.prop`
`7.` system properties have types, they don't have to be strings

@CloudSlang/slang-functional-reviewers please give feedback

**Comment by orius123** [comment]
:+1:

**Comment by meshipeer** [comment]
lets go with the functional access style (to support sensitive data soon)

**Comment by avigail-oron** [comment]
some questions:
#1 - so how will SP be used as inputs?
#6 - why not enforce folder structure? very confusing IMO. is there a reason for that?
#7 - if the SPs are not necessarily strings, how will the users of the SP know how to use it (when referring to it in a flow)?  
@meshipeer - do we include designing the sensitive values solution at this phase? if so we need to discuss the access syntax

**Comment by Bonczidai** [comment]
I would also go with the function style (`2`)

@avigail-oron , regarding your Qs:
`1` SP can be assigned directly in the expression:
```yaml
- input: ${ get_system_property('cloudslang.user.name', 'default value') }
```

`6` I think, with the current approach, enforcing SP folder structure is not a good idea: SP files are plain yaml files, which can hold **multiple** SPs, and can be anywhere in the file system
e.g. 
```yaml
cloudslang.user.name: john doe
cloudslang.user.age: 23
cloudslang.config.location: /usr/config
a.b.c.limit: 5
```
in this case I would need to split this file in three, under three folder: `user`, `config` and `c` - I don't see value in it yet

`#7` just like in inputs files, they can be any type supported by Yaml - e.g. flow inputs are not necessary strings (and we don't declare types explicitly) -- do you think we should limit SP to be only strings?

**Comment by Bonczidai** [comment]
if no more comments, I will start the implementation with the initial approach (in function style)

regarding sensitive data solution, we do not include it in this phase

**Comment by Bonczidai** [comment]
@orius123 ,

I am *considering* moving to PythonInterpreter (what we use for python actions) from ScriptEngine for expressions: 
- API is more flexible, fewer limitations: with Python interpreter I can save "static" stuff as initial context (like `get` function) - with ScriptEngine seem that is not possible
- function definition style:
with ScriptEngine:
```
engine.eval(func1)
engine.eval(func2)
engine.eval(func3)
engine.eval(expr)
```
with PythonInterpreter:
```
interpreter.exec(func1 func2 func3)
interpreter.eval(expr)
```
second approach is more efficient
- execution time: e.g. simple string ('abc'): interpreter (9 ms), scriptEngine (12 ms)

agree that ScriptEngine is cool abstraction (it uses PythonInterpreter underneath, you can change scripting language with one line), but things are starting to get too complex for it

WDYT?

**Comment by orius123** [comment]
If we will want to add other languages in the future this lack of abstraction is not what that will stop it.. 
Until now there was no real reason to lose it though. 25% decrease in performance sounds like a good reason for me.

**Comment by Bonczidai** [comment]
Updated spec:
```
Requirements:

1. no system property in input DSL - no such construct:

-input:
   system_property: cloudslang.user.name

2. system properties will be accessible in input and task argument expressions
- also accessable in outputs, results expressions
- not accessable directly in python actions,`for` and `async` loop expressions
- access style: function -> `${ get_sp('system.property') }`
3. system properties are not enforced at compile time, they will be assigned at runtime
4. system properties are read only
5. system property files are .sl files with namespace (no enforcing, best practice):
    When I have the following hierarchy:
      <properties_folder>/folderA/folderB/properties.sl
    With the content:
    namespace: folderA.folderB

    properties:
        docker.host: 'localhost'
        docker.pass:
          default: 'secret_value'
          sensitive: true

    I’ll get the following objects:
    obj1:
      - key: folderA.folderB.docker.host
      - value: localhost
      - sensitive: false
      
    obj2:
      - key: folderA.folderB.docker.pass
      - value: *******
      - sensitive: true
7. system property values are strings
```

also, we will do benchmarking to see what is the performance impact of adding functions directly to python context (like `get_sp()`)
