### ISSUE TITLE
Flow description similar to javadoc

### ISSUE THREAD

**Issue by gituser173** [CloudSlang/cloud-slang#545]
After internal discussions we reached the conclusion that we have two options:
First would be to mark every line with two characters "#!" so we know which lines contain the description. 
```yaml
#   (c) Copyright 2016 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################
#! @description: general desc
#! @input input1_name: input1 desc
#! @input input2_name: input2 description
#!                     optional
#!                     default: default value
#!                     valid: valid values
#!                     example: example value
#! @output output1_name: output1 desc
#! @result result1_name: result1 desription
#! @result result2_name: result2 description
####################################################

imports:
  containers: io.cloudslang.docker.containers

flow:
  name: create_cluster
```
The second option would be to mark the beginning and the ending of the description block with "#!" or with some other character combination.
 ```yaml
#   (c) Copyright 2016 Hewlett-Packard Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
####################################################
#! 
# @description: general desc
# @input input1_name: input1 desc
# @input input2_name: input2 description
#                     optional
#                     default: default value
#                     valid: valid values
#                     example: example value
# @output output1_name: output1 desc
# @result result1_name: result1 desription
# @result result2_name: result2 description
#!
####################################################

imports:
  containers: io.cloudslang.docker.containers

flow:
  name: create_cluster
```
@CloudSlang/slang-functional-reviewers please give your feedback
