### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#571]
Consider two tasks with the same name like this:

```
  workflow:
    - TASK1:
        do:
          nav_op: []

    - on_failure:
      - TASK1:
          do:
            nav_op: [nr: 1]
```

infinite loop
