### ISSUE TITLE
A flow with a Boolean name or numerical name (no letters in the name except numbers) will fail in CloudSlang

### ISSUE THREAD

**Issue by milanafinkel** [CloudSlang/cloud-slang#626]
**ACTUAL BEHAVIOR: **
*A user can't name a flow with Boolean ("true"/"false"..) in CloudSlang. Using Boolean as a floe name, will make CloudSlang fail.
This error will appear:
`Command failed java.lang.RuntimeException: java.lang.RuntimeException: Error transforming source: false to a Slang model. java.lang.Boolean cannot be cast to java.lang.String`

*A user can't name a flow only with a numerical value in (0,1,2...) Using a numerical value as a flow name, will make CloudSlang fail.
This error will appear:
`Command failed java.lang.RuntimeException: java.lang.RuntimeException: Error transforming source: true to a Slang model. java.lang.Boolean cannot be cast to java.lang.String`

**EXPECTED BEHAVIOR: **
User should be able to use any value as a flow's name.

**HOW-TO-REPRODUCE:**
1. Use the files "new_hire.sl" and "print.sl":

______________________________________
new_hire.sl

```
namespace: tutorials.hiring

imports:
  base: tutorials.base

flow:
  name: new_hire

  workflow:
    - print_start:
        do:
          base.print:
            - text: "Starting new hire process" 
```
_______________________________________
print.sl

```
namespace: tutorials.base

operation:
  name: print

  inputs:
    - text

  action:
    python_script: print text
```
_______________________________________

2. Use this command in the CLI :
`run --f <folder path>/tutorials/hiring/new_hire.sl --cp <folder path>/tutorials/base` , and see that the flow runs properly.
3. Change the name under "flow" in the "new_hire.sl' file to "true".
4. Change the name of the file to true.sl
5. change the run syntex to run --f <folder path>/tutorials/hiring/true.sl --cp <folder path>/tutorials/base 

**
ENVIRONMENT:** (Hardware, OS, OS Version, Browser, etc) 
Tested on Windoew 10 64bit , we bstudio with CLI v. 0.9.50.0
