### ISSUE TITLE
Support input types in CS

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#673]
**[APPROACH I - STRINGS]** go with string interface for now, support types later

**Comment by Bonczidai** [comment]
Functional spec:
- for now we will only support string type in CloudSlang for executable interface
- verification is done at runtime
- executable input / output need to be resolved to string after binding (no implicit casting)
- step input / publish value need to be resolved to string after binding (no implicit casting)
- action outputs are available in operation outputs and results section as objects (no change)
- loops: TBD

p.s. executable = flow / op

**Comment by Bonczidai** [comment]
examples:

```yaml
operation:
  name: print

  inputs:
    - input_1 # fails if not string
    - input_2: '123'
    - input_3: 123 # fails

  action:
    python_script: |
      val_int = 123
      val_str = 'abc'
      val_bool = True

  outputs:
    - output_1 # fails if output_1 is not string
    - output_2: 'hello'
    - output_3: val_bool # fails
    - output_4: str(val_bool)

  results:
    - SUCCESS: ${text != 'fail'}
    - FAILURE
```

```yaml
flow:
  name: print_flow

  workflow:
    - step_name:
        do:
          executable_name:
            - input_1 # fails if not string
            - input_2: 123 # fails
            - input_3: '123'
        publish:
          - publish_int: 123 # fails
          - publish_str: 'abc'
```

**Comment by Bonczidai** [comment]
for loop example:

```yaml
flow:
  name: print_flow
  inputs:
    - list_as_str: '1 2 3'

  workflow:

  - print_message:
      loop:
        for: nr in list_as_str.split() # `list_as_str` also works
        do:
          print:
            - text: ${nr}
```

basically we need a delimiter and convert vice-versa between string and array representations (e.g. join(), split() functions)

**Comment by orius123** [comment]
Y

**Comment by Bonczidai** [comment]
**[APPROACH II - TYPES]**

- Current supported types: String \ Number \ Boolean \ Object (this will also give us in the future ability to support more complex types like dates)
- Default type (if not specified) is String 
- we want to validate the type during the binding (runtime - e.g. at the beginning of the flow \ operation)
- no implicit type conversion: 123 for String input fails, '123' passes
- if type is not correct -> illegal argument – type mismatch message
- during the flow the type might change (e.g. using the publish section) – we do not validate it!
- we will validate primitive default value is of specified type (compile time):
```
- input_key:
    default: 123 # fails
    type: string
```

examples:

```yaml
operation:
  name: print

  inputs:
    - input_1 # type: string
    - input_2: '123'
    - input_3: 123 # fails
    - input_4:
         default: 123
         type: Number
    - input_5:
         default: [1,2,3]
         type: Object

  action:
    python_script: |
      val_int = 123
      val_str = 'abc'
      val_bool = True

  outputs:
    - output_1 # fails if output_1 is not string
    - output_2: 'hello'
    - output_3: 
         default: val_bool
         type: Boolean

  results:
    - SUCCESS: ${val_str != 'fail'}
    - FAILURE
```

@CloudSlang/slang-functional-reviewers WDYT?
