### ISSUE TITLE
on_failure section

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#704]
to discuss on_failure section - now it can be anywhere in the workflow section, contains only one step, you can navigate to it either by `on_failure` keyword or step name

```yaml
workflow:
  - step1
  - on_failure:
       - step3
  - step2
```

- force `on_failure` to be last step in the workflow section?
- different section like `workflow`?
