### ISSUE TITLE
Validation of navigation should be done in the preCompile phase

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#732]
When the navigation is to a non-existing step or flow result, the `preCompile()` passes, only the `compile()` fails
The validation should be during the preCompile phase
Example:

```yaml
namespace: a.b
flow: 
  name: flow    
  workflow: 
    - step1: 
        do: 
          flow2: 
            - text 
        navigate: 
          - SUCCESS: non_existing_step
          - FAILURE: null
```
