### ISSUE TITLE
Flow with invalid flow inputs should fail pre-compilation

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#735]
The following flow has invalid flow inputs section, but it passes the `preCompile()`

```yaml
namespace: folder
 inputs:
    - input1: {}
      input2:
        private: true
flow:
  name: name
  workflow:
    - run_command:
        do:
          io.cloudslang.base.cmd.run_command:
            - command
```
