### ISSUE TITLE
support desicion

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#767]

**Comment by Bonczidai** [comment]
- decision is a new type of executable: flow, op, decision
- interface is similar to executable: it will have namespace, name, inputs, outputs, results
  - diff: since it is a decision, it will not have default results (SUCCESS / FAILURE), you need to define explicitly
- can hold regular language elements like description, extension section
- can be called in a step as a regular executable
- will be an .sl file

example - if.sl:
```yaml
namespace: a.b

decision:
  name: compare

  inputs:
    - x
    - y

  outputs:
    - sum: ${x+y}

  results:
    - EQUAL: ${x == y}
    - LESS_THAN: ${x < y}
    - GREATER_THAN
```

called in a flow:

```yaml
    - decision_1:
        do:
          compare: [x, y]
        publish:
          - save_for_later: ${sum}
        navigate:
          - EQUAL: ..
          - LESS_THAN: ..
          - GREATER_THAN: ..
```
