### ISSUE TITLE
Missing validation of default navigation causes NPE

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#771]
```
namespace: user.flows

imports:
  ops: user.ops
  decisions: user.decisions

flow:
  name: flow_with_decision_1
  inputs:
    - x
    - y
  workflow:
    - op1:
        do:
          ops.noop: []

    - op2:
        do:
          ops.noop: []
        navigate:
          - SUCCESS: EQUAL
          - FAILURE: LESS_THAN
  results:
    - EQUAL
    - LESS_THAN
```

fails with NPE: it is not validated that the flow declares the first steps's results (default -> SUCCESS / FAILURE), in the background it thinks it's a step
