### ISSUE TITLE
when adding sensitive output to flow, the flow become to invalid - fail in compilation

### ISSUE THREAD

**Issue by haimyyy** [CloudSlang/cloud-slang#785]
Hi, 

I'm from WebStudio Guy Team, I found some issue while adding sensitive output (without value!).
Please have a look at the following Yaml, that fail in compilation with error:  
`> [ERROR] Output: flow_output_1 was not specified`

```
#!!
#! @output flow_output_0: aaaa
#!!#
namespace: ss
flow:
  name: qqq
  inputs:
    - flow_input_0:
        default: '${flow_input_1}'
    - flow_input_1:
        default: "${get_sp('io.cloudslang.base.http.keystore_password')}"
  workflow:
    - bootstrap_node:
        do:
          io.cloudslang.chef.bootstrap_node:
            - node_name: '${aaaa}'
            - node_host: '${ssss}'
            - node_username: '${ddd}'
            - knife_host: '${aaaa}'
            - knife_username: '${ddd}'
        navigate:
          - FAILURE: on_failure
          - SUCCESS: SUCCESS
  outputs:
    - flow_output_0:
        value: '${flow_input_1}'
        sensitive: true
    - flow_output_1:
        sensitive: true
  results:
    - FAILURE
    - SUCCESS
extensions:
  graph:
   steps:
      bootstrap_node:
        x: 201
        y: 223
   results:
      SUCCESS:
        d49d9ac2-f6af-a239-af70-2d23e5fe85a1:
          x: 536
          y: 199
   navigations:
      0021fa3e-4d42-41aa-9a61-48c0ac55c09f:
        name: SUCCESS
        sourceId: bootstrap_node
        sourcePortName: SUCCESS
        targetId: d49d9ac2-f6af-a239-af70-2d23e5fe85a1
```

Thanks,
Haim
