### ISSUE TITLE
Issue when using Queue class in the python script

### ISSUE THREAD

**Issue by victorursan** [CloudSlang/cloud-slang#794]
replicating script:
``` YAML
operation:
  name: test_queue
  inputs:
    - some_value:
       default: "123"
       required: false
  python_action:
   script: |
     from Queue import Queue
     queue = Queue()
     queue.put(some_value)
     result_queue = str(queue.get())
  outputs:
    - return_result: ${result_queue}
    - error_message
  results:
    - SUCCESS
    - FAILURE

```

error:
![image](https://cloud.githubusercontent.com/assets/1898539/17056047/8b804210-5019-11e6-8b6f-7c80e3155689.png)

possible reason:
_Queue_ doesn't have any constructors in the _jython_ generated _java_ code from the script
