### ISSUE TITLE
Step/Result should not accept name on failure

### ISSUE THREAD

**Issue by SamyQA** [CloudSlang/cloud-slang#796]
Step/result cannot be called on-failure

Step: “Below 'on_failure' property there should be a list of steps and not a map” – this error message should be improved
Result: the check does not work

Expected:
No step or response should be called 'on_failure' or any other case combination e.g.: 'ON_Failure', 'ON_FAILURE' etc 
Relevant message should be displayed at compilation

**Comment by Bonczidai** [comment]
@SamyQA ,

for steps I don't think we can apply the error message suggested, because of CloudSlang syntax

e.g.

```
workflow:
  - step_1: ... # step 1 data
  - on_failure: ... # step data, I named the step on_failure # case 1
  - on_failure: ... # on_failure section, I put incorrect data # case 2
```

case 1, case 2 -- how do I know the difference? I don't
