### ISSUE TITLE
Private, required input with empty string default value should fail preCompile

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#840]
```yaml
    - input_1:
        required: true
        private: true
        default: ''
```

passes compilation, should fail
