### ISSUE TITLE
Required input with value of empty string should be invalid

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#842]

**Comment by Bonczidai** [comment]
is this duplicate with #840 ?

**Comment by oritstone** [comment]
When a step has a required input with a value of empty string, it should fail compilation:
```yaml
- step1:
    do:
       op1:
          - input1: ''
```
Also, if we do not refer tp that required input in the step and it has a default value of empty string in the subflow, it should also fail
```yaml
- step1:
    do:
       op1:
```

Where:
```yaml
op1:
  inputs:
    - input1: ''
```
