### ISSUE TITLE
Parallel loop failed with rest calls

### ISSUE THREAD

**Issue by mikelzuzu** [CloudSlang/cloud-slang#959]
Hello to everyone,

I'm trying to use CS to make several rest calls to some of my microservices. The point is that I need to make some of them in parallel to make it faster and the parallel loop fails if in the same flow there is a previous step doing another rest call. The following flow is an example to reproduce the issue that I'm having. In this way anyone can test locally. 

```yaml
namespace: io.cloudslang

imports:
  rest: io.cloudslang.base.http
  print: io.cloudslang.base.print
  json: io.cloudslang.base.json

flow:
  name: pets

  inputs:
    - url:
        required: false
        default: 'http://petstore.swagger.io/v2/pet'
    - content_type:
        default: "application/json"
    - body:
        default: "${'{ \"id\": 0,\"category\": { \"id\": 0, \"name\": \"string\" }, \"name\": \"doggie\", \"photoUrls\": [ \"string\" ], \"tags\": [ { \"id\": 0, \"name\": \"string\" } ], \"status\": \"available\"}'}"
  workflow:
    - add_pet:
        do:
          rest.http_client_post:
            - url: ${url}
            - content_type: ${content_type}
            - body: ${body}
        publish:
          - answer: ${status_code}
          - result: ${return_result}
          - error: ${error_message}
        navigate:
          - SUCCESS: get_id
          - FAILURE: FAILURE
    - get_id:
        do:
          json.get_value:
            - json_input: ${result}
            - json_path: "id"
        publish:
          - id: ${return_result}
        navigate:
          - SUCCESS: printer
          - FAILURE: FAILURE
    - printer:
        do:
          print.print_text:
            - text: ${id}
        navigate:
          - SUCCESS: get_pets
    - get_pets:
        parallel_loop:
          for: x in range(1, 3)
          do:
            rest.http_client_get:
              - url: ${url+'/'+id}
        publish:
          - pets: ${', '.join(filter(lambda x:x != '', map(lambda x:str(x['return_result']), branches_context)))}
        navigate:
          - SUCCESS: get_again_pet
          - FAILURE: FAILURE
    - get_again_pet:
        do:
          rest.http_client_get:
            - url: ${url+'/'+id}
        publish:
          - pet: ${return_result}
        navigate:
          - SUCCESS: SUCCESS
          - FAILURE: FAILURE
  outputs:
    - result: ${pet}
  results:
    - SUCCESS
    - FAILURE
```

I am using the CLI (1.0.0. , 1.0.2 and 1.0.3-SNAPSHOT) to test this flow and this is the output:
![result](https://cloud.githubusercontent.com/assets/9826219/20748879/e8413114-b6e7-11e6-8aa4-85cb128a875b.png)

I found this issue just if I have a previous step using the HttpClientAction and then the parallel loop calling to the same class.

Am I doing something wrong? I am new in CS so it could be...

By the way, I was debugging remotely and for me is failing around in the package 'io.cloudslang.runtime.impl.java' there is a class  called 'JavaExecutor'. When it is tried to execute the method invoke in the line 93 it's failing and not reaching HttpClientAction.

Thanks in advance,

Mikel
