### ISSUE TITLE
Cloudslang reports unreachable result for flow

### ISSUE THREAD

**Issue by cid77** [CloudSlang/cloud-slang#968]
```yaml
namespace: AAA
flow:
  name: f1
  workflow:
    - SUCCESS:
        do:
          io.cloudslang.base.utils.uuid_generator: []
        navigate:
          - SUCCESS: SUCCESS
  results:
    - SUCCESS
extensions:
  graph:
    steps:
      SUCCESS:
        x: 129
        y: 143
        navigate:
          6f750ec8-47e6-cdca-944e-941f175aa097:
            targetId: b63b6319-6bd9-dbd3-b5e9-ded9c5136856
            port: SUCCESS
    results:
      SUCCESS:
        b63b6319-6bd9-dbd3-b5e9-ded9c5136856:
          x: 473
          y: 121

```
