### ISSUE TITLE
Support modifiers on step level

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#973]
- for now: `value` and `sensitive`
- syntax is similar with the `inputs`
```yaml
- step_input: val
```
~
```yaml
- step_input:
     value: val
```
~
```yaml
- step_input:
     value: val
     sensitive: false
```
- no value tag case:
```yaml
- step_input:
     sensitive: <value>
```
~
```yaml
- step_input:
     value: ${step_input} # assign based on name
     sensitive: <value>
```
- sensitivity has default value of `false`
- we can set the flag with the `sensitive` modifier:
```yaml
- step_input:
     value: val
     sensitive: true
```

- behavior is similar to those of flow inputs, outputs and SPs:
  - modifier controls compile time sensitivity
  - at runtime transitivity overrides compile time sensitivity
  - encryption and obfuscation will be handled in the same way as for the upper items

refresher - behavior that remains the same:
- steps inputs are by default not required (they can be evaluated to `null`)
- step inputs are similar to flow inputs that are private (meaning, if you supply a value for a step input - it will have that value - value from flow context cannot override it - similar behavior to function calls - that's way we use `value` modifier instead of `default`)
- syntax `- step_input` (without value) assigns a variable from flow context
