### ISSUE TITLE
Description for steps

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#976]
```yaml
  workflow:
    ##########################################################################################
    #!!
    #! @input url: Hostname or IP address.
    #! @input auth_type: auth_type or IP address.
    #! @input username: username or IP address.
    #!
    #! @output return_result: STDOUT of the remote machine in case of success or the cause in
    #!                        in case of success or the cause of the error in case
    #! @output error_message: STDOUT of the machine in case of successful request
    #!!#
    ##########################################################################################
    - http_client_action_get:
        do:
          http.http_client_action:
            - url
            - auth_type: ${ get_sp(retrieve_my_awesome_sp(a, 1224332423), 'default_value') }
            - username
        publish:
          - return_result
          - error_message
```
