### ISSUE TITLE
Conditional String publish based on Navigation result

### ISSUE THREAD

**Issue by sarfaras** [CloudSlang/cloud-slang#978]
Please tell me how can I,
- Conditionally assign/publish a value in workflow based on navigation result from an operation
Scenario is, Flow is going through different navigation route but finally I have to generate a user message where I have to call an operation generate message but only that I have to pass "currentState". I just want to limit invocation to "GenerateMessage" only in one place in flow but dynamically assign "currentState" variable in flow. Right now the challenge I have is, how do i achieve
 Call OP1
    Publish "currentState" = "OP1 Failed" if OP1 failed (based on navigation result)
    Publish "currentState" = "OP2 Failed" if OP2 successful
    Publish "currentState" = "State1" if returnCode = 2

I know 3rd can be achieved with an equals operation but that seems to be lot to do to achieve small thing. Also I dont see an option for first two cases where I have to set a variable based on navigation result from operation. Thanks

**Comment by Bonczidai** [comment]
good point

- you can e.g.
```yaml
  workflow:
    - op:
        do:
          ops.op: ..
        publish:
          - currentState: ${ 'OP2 Failed' if <FAILURE_CONDITION_FROM_OPERATION> else 'STATE1' }
        navigate:
          - EVEN: ..
```
do it with a Python expression - however in this case, you have to duplicate the result condition from the operation (which is not so good if the underlying op changes)

- you can introduce an additional step (noop) to define your variables in its publish section and then navigate to the `GenerateMessage` step
- or use two `Generate message' steps:
```yaml
  workflow:
    - op1:
        do:
          ops.op: ..
        publish:
          - failure_message: # set failure message

    - op2:
        do:
          ops.op: ..
        publish:
          - success_message: # set success message
          - failure_message: # set failure message
          
    - generate_success_message:
        do:
          ops.generate:
            - message: success_message

    - on_failure:
      - generate_failure_message:
          do:
            ops.generate:
              - message: failure_message
```
see [on_failure here](http://cloudslang-docs.readthedocs.io/en/v1.0/cloudslang_dsl_reference.html#on-failure)

but, overall I think it would make a valid enhancement what you are suggesting
